// Auto-generated by seed.ts — do not edit manually
import type { DataSource } from "@/types";

export const dataSources: DataSource[] = [
	{
		id: "parlament-ch",
		name: "parlament.ch",
		url: "https://www.parlament.ch",
		description:
			"Offizielle Daten des Schweizer Parlaments - Ratsmitglieder und Interessenbindungen",
		last_synced: "2026-02-26T22:00:00Z",
	},
	{
		id: "zefix",
		name: "Zefix / Handelsregister",
		url: "https://www.zefix.admin.ch",
		description:
			"Schweizerisches Handelsamtsblatt - Verwaltungsratsmandate und Unternehmensstrukturen",
		last_synced: "2026-02-22T03:00:00Z",
	},
	{
		id: "lobbywatch",
		name: "Lobbywatch.ch",
		url: "https://lobbywatch.ch",
		description: "NGO-Daten uber Lobbyismus im Bundeshaus",
		last_synced: "2026-02-26T18:00:00Z",
	},
	{
		id: "eidg-kanzlei",
		name: "Eidgenossische Bundeskanzlei",
		url: "https://www.bk.admin.ch",
		description: "Transparenz politischer Finanzierung und Abstimmungskomitees",
		last_synced: "2026-02-21T18:00:00Z",
	},
	{
		id: "media",
		name: "Medienberichte",
		url: "",
		description: "Verbindungen aus offentlichen Medienberichten",
		last_synced: "2026-01-15T08:30:00Z",
	},
];
